spring.application.name=test
# Cau hinh PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Web-Ecommere
spring.datasource.username=postgres
spring.datasource.password=duc8504
spring.datasource.driver-class-name=org.postgresql.Driver

# Payment gateway
payment.gateway.apiKey=your_api_key_here
payment.gateway.secretKey=your_secret_key_here
payment.gateway.baseUrl=https://api.payment.com

# JPA Hibernate
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.enable_lazy_load_no_trans = true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tryItOutEnabled=true

logging.level.org.springframework.http.converter.json=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

file.upload-dir=uploads/
server.base-url=http://localhost:8080
#spring.web.resources.static-locations=classpath:/static/,file:uploads/
spring.web.resources.static-locations=file:uploads/

payos.client-id=695c5847-7287-4ba7-9703-785b548cda0a
payos.api-key=d293ec08-10ea-40f6-8bb9-a50e2c4f4d9d
payos.checksum-key=9fab6fd91798e1edf7117e1469f86d80641eeec37521eabcb55634733cd18ff3
payos.api-url=https://api-merchant.payos.vn

payos.return-url=http://localhost:3000/payment/success
payos.cancel-url=http://localhost:3000/payment/cancel

#ALT + J => pick many sentence